# Generated by Django 4.0.4 on 2022-05-31 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_remove_aboutme_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.skill'),
        ),
    ]
