# Generated by Django 4.0.4 on 2022-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_aboutme_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='skill',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.skill'),
        ),
    ]
