# Generated by Django 4.0.4 on 2022-06-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_aboutme_skill_aboutme_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='skill',
            field=models.ManyToManyField(blank=True, to='portfolio.skill'),
        ),
    ]
