# Generated by Django 4.0.4 on 2022-06-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resume'},
        ),
    ]
