# Generated by Django 4.0.4 on 2022-06-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_resume_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='work_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
