# Generated by Django 4.0.4 on 2022-06-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_resume_work_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
