# Generated by Django 4.0.4 on 2022-06-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_resume_file_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
