# Generated by Django 4.0.4 on 2022-06-02 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_aboutme_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='about_me',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
