# Generated by Django 4.0.4 on 2022-06-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_aboutme_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.CharField(blank=True, max_length=111, null=True)),
                ('education_name', models.CharField(blank=True, max_length=150, null=True)),
                ('education_information', models.TextField(blank=True, null=True)),
                ('date_education', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(blank=True, max_length=111, null=True)),
                ('work_position', models.CharField(blank=True, max_length=100, null=True)),
                ('work_information', models.TextField(blank=True, null=True)),
                ('date_work', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='date_education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='date_work',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_information',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_information',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_position',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_title',
        ),
    ]
