# Generated by Django 4.0.4 on 2022-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_education_work_remove_resume_date_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
